begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 2 and 24),
  city text check (city is null or char_length(city) <= 30),
  supporter_years text check (supporter_years is null or char_length(supporter_years) <= 40),
  role text not null default 'member' check (role in ('member','moderator','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  author_name text not null check (char_length(author_name) between 2 and 24),
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  author_name text not null check (char_length(author_name) between 2 and 24),
  body text not null check (char_length(body) between 1 and 400),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.post_reactions (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null default 'heart' check (reaction in ('heart')),
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  fixture_key text not null check (char_length(fixture_key) between 3 and 80),
  home_score smallint not null check (home_score between 0 and 20),
  away_score smallint not null check (away_score between 0 and 20),
  comment text check (comment is null or char_length(comment) <= 400),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, fixture_key)
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint references public.posts(id) on delete cascade,
  comment_id bigint references public.comments(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 200),
  status text not null default 'open' check (status in ('open','reviewing','closed')),
  created_at timestamptz not null default now(),
  check ((post_id is not null) <> (comment_id is not null))
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, nickname, city, supporter_years)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'nickname',''),
      nullif(new.raw_user_meta_data ->> 'full_name',''),
      nullif(new.raw_user_meta_data ->> 'name',''),
      'Tifoso TB'
    ),
    nullif(new.raw_user_meta_data ->> 'city',''),
    nullif(new.raw_user_meta_data ->> 'supporter_years','')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.post_reactions enable row level security;
alter table public.predictions enable row level security;
alter table public.reports enable row level security;

drop policy if exists "profiles readable by everyone" on public.profiles;
create policy "profiles readable by everyone" on public.profiles for select using (true);
drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "published posts readable by everyone" on public.posts;
create policy "published posts readable by everyone" on public.posts for select using (deleted_at is null);
drop policy if exists "users create own posts" on public.posts;
create policy "users create own posts" on public.posts for insert with check (auth.uid() = user_id);
drop policy if exists "users update own posts" on public.posts;
create policy "users update own posts" on public.posts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users delete own posts" on public.posts;
create policy "users delete own posts" on public.posts for delete using (auth.uid() = user_id);

drop policy if exists "comments readable by everyone" on public.comments;
create policy "comments readable by everyone" on public.comments for select using (deleted_at is null);
drop policy if exists "users create own comments" on public.comments;
create policy "users create own comments" on public.comments for insert with check (auth.uid() = user_id);
drop policy if exists "users edit own comments" on public.comments;
create policy "users edit own comments" on public.comments for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users delete own comments" on public.comments;
create policy "users delete own comments" on public.comments for delete using (auth.uid() = user_id);

drop policy if exists "reactions readable by everyone" on public.post_reactions;
create policy "reactions readable by everyone" on public.post_reactions for select using (true);
drop policy if exists "users create own reactions" on public.post_reactions;
create policy "users create own reactions" on public.post_reactions for insert with check (auth.uid() = user_id);
drop policy if exists "users delete own reactions" on public.post_reactions;
create policy "users delete own reactions" on public.post_reactions for delete using (auth.uid() = user_id);

drop policy if exists "predictions readable by everyone" on public.predictions;
create policy "predictions readable by everyone" on public.predictions for select using (true);
drop policy if exists "users create own predictions" on public.predictions;
create policy "users create own predictions" on public.predictions for insert with check (auth.uid() = user_id);
drop policy if exists "users update own predictions" on public.predictions;
create policy "users update own predictions" on public.predictions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "users create reports" on public.reports;
create policy "users create reports" on public.reports for insert with check (auth.uid() = reporter_id);
drop policy if exists "users read own reports" on public.reports;
create policy "users read own reports" on public.reports for select using (auth.uid() = reporter_id);

create table if not exists public.consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  policy_version text not null check (char_length(policy_version) between 1 and 20),
  privacy_accepted boolean not null default false,
  community_rules_accepted boolean not null default false,
  age_declaration text not null check (age_declaration in ('14_or_parental_authorization')),
  accepted_at timestamptz not null default now(),
  user_agent text check (user_agent is null or char_length(user_agent) <= 300),
  unique (user_id, policy_version)
);

create table if not exists public.privacy_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  request_type text not null check (request_type in ('access','rectification','export','restriction','deletion')),
  details text not null check (char_length(details) between 5 and 500),
  status text not null default 'received' check (status in ('received','processing','completed','rejected')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.consents enable row level security;
alter table public.privacy_requests enable row level security;

drop policy if exists "users record own consent" on public.consents;
create policy "users record own consent" on public.consents for insert with check (auth.uid() = user_id);
drop policy if exists "users update own consent" on public.consents;
create policy "users update own consent" on public.consents for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users read own consent" on public.consents;
create policy "users read own consent" on public.consents for select using (auth.uid() = user_id);

drop policy if exists "users create privacy requests" on public.privacy_requests;
create policy "users create privacy requests" on public.privacy_requests for insert with check (auth.uid() = user_id);
drop policy if exists "users read own privacy requests" on public.privacy_requests;
create policy "users read own privacy requests" on public.privacy_requests for select using (auth.uid() = user_id);

do $$
begin
  alter publication supabase_realtime add table public.posts;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.comments;
exception when duplicate_object then null;
end $$;

commit;
