const SOURCE_ORIGIN='https://www.corrieredellosport.it';
const KNOWN_MATCHES=['/live/partita/bari-potenza-2677048','/live/partita/team-altamura-bari-2675598'];
function decodeHtml(v=''){const n={amp:'&',quot:'"',apos:"'",lt:'<',gt:'>',nbsp:' ',agrave:'à',egrave:'è',eacute:'é',igrave:'ì',ograve:'ò',ugrave:'ù',deg:'°'};return v.replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#([0-9]+);/g,(_,x)=>String.fromCodePoint(parseInt(x,10))).replace(/&([a-z]+);/gi,(e,x)=>n[x.toLowerCase()]??e).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function isBariMatchPath(path){const s=path.split('/').pop()||'';return/(?:^|-)bari(?:-|$)/i.test(s)}
function findMatchPaths(html){const out=[];for(const m of html.matchAll(/href="(\/live\/partita\/[^"]+)"/g)){const p=decodeHtml(m[1]);if(isBariMatchPath(p)&&!out.includes(p))out.push(p)}return out}
function periodLabel(p,m){if(p==='FirstHalf')return`${m||1}' 1° tempo`;if(p==='HalfTime')return'Intervallo';if(p==='SecondHalf')return`${m||46}' 2° tempo`;if(p==='ExtraTimeFirstHalf'||p==='ExtraTimeSecondHalf')return`${m||''}' supplementari`.trim();if(p==='PenaltyShootout')return'Calci di rigore';if(p==='FullTime')return'Finale';return''}
function parseMatchData(payload,source){const r=payload?.matchresults,f=r?.fixtures,l=r?.live,i=l?.MatchInfo;if(!f||!l||!i)return null;const periods=new Set(['FirstHalf','HalfTime','SecondHalf','ExtraTimeFirstHalf','ExtraTimeSecondHalf','PenaltyShootout']);const raw=payload?.commentary?.commentary?.elements?.[0]?.elements||[];const salient=new Set(['goal','penalty goal','own goal','yellow card','second yellow','red card','substitution','kick off','half time','full time','attempt saved','attempt blocked','attempt missed','corner','penalty','start delay','end delay']);const events=raw.slice(0,160).map(x=>{const a=x?.attributes||{};return{minute:String(a.time||(a.minute?`${a.minute}'`:'')),text:String(a.comment||''),salient:salient.has(String(a.type||'').toLowerCase())}}).filter(x=>x.minute&&x.text);return{live:periods.has(i.Period),finished:i.Period==='FullTime',competition:f.cName||'Serie C · Girone C',home:f.home_name||'Casa',away:f.away_name||'Bari',score:`${l.score_home??0} - ${l.score_away??0}`,status:periodLabel(i.Period,i.MatchTime),matchDate:f?.date?.dateUTC||'',events,source,sourceName:'Corriere dello Sport · dati Opta',updatedAt:payload.lastUpdate||new Date().toISOString()}}
function isRecentFinal(m){if(!m?.finished)return false;const t=Date.parse(m.updatedAt||m.matchDate||'');return Number.isFinite(t)&&Date.now()-t<12*60*60*1000}
async function fetchPage(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; TreninoBari/1.1; +https://treninobari.vercel.app)',accept:'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Fonte live non disponibile (${r.status})`);return r.text()}
async function fetchMatchData(id,path=''){const r=await fetch(`${SOURCE_ORIGIN}/api-live/matchresults/${id}`,{headers:{'user-agent':'Mozilla/5.0 (compatible; TreninoBari/1.1; +https://treninobari.vercel.app)',accept:'application/json'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Dati live non disponibili (${r.status})`);return parseMatchData(await r.json(),path?new URL(path,SOURCE_ORIGIN).href:`${SOURCE_ORIGIN}/live`)}
function matchIdFromPath(path){return(path.match(/-([0-9]+)$/)||[])[1]||''}
module.exports=async function handler(req,res){res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, s-maxage=10, stale-while-revalidate=20');try{let paths=[];try{paths=findMatchPaths(await fetchPage(`${SOURCE_ORIGIN}/live`))}catch(_){}paths=[...new Set([...paths,...KNOWN_MATCHES])];for(const path of paths.slice(0,10)){const id=matchIdFromPath(path);if(!id)continue;try{const data=await fetchMatchData(id,path);if(data?.live||isRecentFinal(data))return res.status(200).json(data)}catch(_){}}return res.status(200).json({live:false,updatedAt:new Date().toISOString()})}catch(error){return res.status(200).json({live:false,unavailable:true,message:error instanceof Error?error.message:'Fonte live non disponibile',updatedAt:new Date().toISOString()})}};
module.exports._findMatchPaths=findMatchPaths;module.exports._parseMatchData=parseMatchData;module.exports._isRecentFinal=isRecentFinal;